remote_theme: pmarsceill/just-the-docs

title: OpenSpace
description: An open-source astrovisualization software
logo: "/assets/images/logo.png"

search_tokenizer_separator: /[\s/]+/
#heading_anchors: true
footer_content: "Copyright &copy; 2014-2021. Distributed by an <a href=\"https://github.com/OpenSpace/OpenSpace/tree/master/LICENSE.md\">MIT license.</a>"
#color_scheme: "dark"

aux_links:
  "OpenSpace on GitHub":
    - "//github.com/OpenSpace/OpenSpace"

collections:
  - theses
  - papers

plugins:
  - jekyll-seo-tag
  - jekyll-avatar
  - jekyll-github-metadata
  - jekyll-feed
  - jekyll-sitemap

github: [metadata]
